PREFIX ecrm: <http://erlangen-crm.org/current/>

SELECT DISTINCT ?fus WHERE {
	{?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/akkadian-and-sumerian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/old-akkadian-sumerian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumerian-akkadian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/bilingual-sumerian-and-akkadian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumerian-or-akkadian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumero-akkadian> }
	UNION { ?fus ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/bilingual:-sumerian-akkadian> }
	}
