PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bmo: <http://collection.britishmuseum.org/id/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

    
SELECT DISTINCT ?theObject ?theInscription ?linkToImage ?objectDescription WHERE {
     
    {?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/akkadian-and-sumerian>. 
     ?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     
     OPTIONAL {?theObject    bmo:PX_has_main_representation  ?linkToImage.    }
     OPTIONAL {?theObject    bmo:PX_physical_description ?objectDescription.}
    }
    
    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/old-akkadian-sumerian>.
            ?theObject    ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {      ?theObject    bmo:PX_has_main_representation  ?linkToImage.  }
     OPTIONAL {      ?theObject    bmo:PX_physical_description ?objectDescription.}
     }

    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumerian-akkadian>.
            ?theObject    ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {    ?theObject     bmo:PX_has_main_representation  ?linkToImage.}  
     OPTIONAL {    ?theObject     bmo:PX_physical_description ?objectDescription.}
    }

    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/bilingual-sumerian-and-akkadian>.
           ?theObject    ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {       ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {     ?theObject    bmo:PX_physical_description ?objectDescription.}
 }

    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumerian-or-akkadian>.
            ?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {     ?theObject     bmo:PX_has_main_representation  ?linkToImage. }  
     OPTIONAL {     ?theObject    bmo:PX_physical_description ?objectDescription.}
 }

    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumero-akkadian>.
           ?theObject    ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject    bmo:PX_has_main_representation  ?linkToImage.  }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
 }

    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/bilingual:-sumerian-akkadian>.
           ?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
    }
    
    UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/sumerian> .
          ?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
    }

UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/imitation-sumerian> .
?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
    }

UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/emesal> .
?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
    }
    
UNION { ?theInscription ecrm:P72_has_language <http://collection.britishmuseum.org/id/thesauri/language/phonetic-sumerian> .
?theObject     ecrm:P65_shows_visual_item   ?theInscription.
     OPTIONAL {   ?theObject     bmo:PX_has_main_representation  ?linkToImage. }
     OPTIONAL {   ?theObject    bmo:PX_physical_description ?objectDescription.}
    }
    } 
    